// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(hnswFFI)
import hnswFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_hnsw_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_hnsw_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureHnswInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol HnswIndexCosineProtocol: AnyObject, Sendable {
    
    func getDimension()  -> UInt32
    
    func insert(data: [Float], id: UInt64) throws 
    
    func insertBatch(data: [[Float]], ids: [UInt64]) throws 
    
    func isEmpty() throws  -> Bool
    
    func len() throws  -> UInt64
    
    func save(directory: String, basename: String) throws 
    
    func search(query: [Float], k: UInt32, efSearch: UInt32) throws  -> [SearchResult]
    
    func setSearchingMode(enabled: Bool) throws 
    
}
open class HnswIndexCosine: HnswIndexCosineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_hnsw_fn_clone_hnswindexcosine(self.handle, $0) }
    }
public convenience init(maxNbConnection: UInt32, maxElements: UInt64, maxLayer: UInt32, efConstruction: UInt32, dimension: UInt32) {
    let handle =
        try! rustCall() {
    uniffi_hnsw_fn_constructor_hnswindexcosine_new(
        FfiConverterUInt32.lower(maxNbConnection),
        FfiConverterUInt64.lower(maxElements),
        FfiConverterUInt32.lower(maxLayer),
        FfiConverterUInt32.lower(efConstruction),
        FfiConverterUInt32.lower(dimension),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_hnsw_fn_free_hnswindexcosine(handle, $0) }
    }

    
public static func load(directory: String, basename: String, dimension: UInt32)throws  -> HnswIndexCosine  {
    return try  FfiConverterTypeHnswIndexCosine_lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_constructor_hnswindexcosine_load(
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),
        FfiConverterUInt32.lower(dimension),$0
    )
})
}
    

    
open func getDimension() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_hnsw_fn_method_hnswindexcosine_get_dimension(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func insert(data: [Float], id: UInt64)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexcosine_insert(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(data),
        FfiConverterUInt64.lower(id),$0
    )
}
}
    
open func insertBatch(data: [[Float]], ids: [UInt64])throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexcosine_insert_batch(
            self.uniffiCloneHandle(),
        FfiConverterSequenceSequenceFloat.lower(data),
        FfiConverterSequenceUInt64.lower(ids),$0
    )
}
}
    
open func isEmpty()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexcosine_is_empty(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func len()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexcosine_len(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func save(directory: String, basename: String)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexcosine_save(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),$0
    )
}
}
    
open func search(query: [Float], k: UInt32, efSearch: UInt32)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexcosine_search(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(query),
        FfiConverterUInt32.lower(k),
        FfiConverterUInt32.lower(efSearch),$0
    )
})
}
    
open func setSearchingMode(enabled: Bool)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexcosine_set_searching_mode(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(enabled),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHnswIndexCosine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HnswIndexCosine

    public static func lift(_ handle: UInt64) throws -> HnswIndexCosine {
        return HnswIndexCosine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HnswIndexCosine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HnswIndexCosine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HnswIndexCosine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexCosine_lift(_ handle: UInt64) throws -> HnswIndexCosine {
    return try FfiConverterTypeHnswIndexCosine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexCosine_lower(_ value: HnswIndexCosine) -> UInt64 {
    return FfiConverterTypeHnswIndexCosine.lower(value)
}






public protocol HnswIndexDotProtocol: AnyObject, Sendable {
    
    func getDimension()  -> UInt32
    
    func insert(data: [Float], id: UInt64) throws 
    
    func insertBatch(data: [[Float]], ids: [UInt64]) throws 
    
    func isEmpty() throws  -> Bool
    
    func len() throws  -> UInt64
    
    func save(directory: String, basename: String) throws 
    
    func search(query: [Float], k: UInt32, efSearch: UInt32) throws  -> [SearchResult]
    
    func setSearchingMode(enabled: Bool) throws 
    
}
open class HnswIndexDot: HnswIndexDotProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_hnsw_fn_clone_hnswindexdot(self.handle, $0) }
    }
public convenience init(maxNbConnection: UInt32, maxElements: UInt64, maxLayer: UInt32, efConstruction: UInt32, dimension: UInt32) {
    let handle =
        try! rustCall() {
    uniffi_hnsw_fn_constructor_hnswindexdot_new(
        FfiConverterUInt32.lower(maxNbConnection),
        FfiConverterUInt64.lower(maxElements),
        FfiConverterUInt32.lower(maxLayer),
        FfiConverterUInt32.lower(efConstruction),
        FfiConverterUInt32.lower(dimension),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_hnsw_fn_free_hnswindexdot(handle, $0) }
    }

    
public static func load(directory: String, basename: String, dimension: UInt32)throws  -> HnswIndexDot  {
    return try  FfiConverterTypeHnswIndexDot_lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_constructor_hnswindexdot_load(
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),
        FfiConverterUInt32.lower(dimension),$0
    )
})
}
    

    
open func getDimension() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_hnsw_fn_method_hnswindexdot_get_dimension(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func insert(data: [Float], id: UInt64)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexdot_insert(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(data),
        FfiConverterUInt64.lower(id),$0
    )
}
}
    
open func insertBatch(data: [[Float]], ids: [UInt64])throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexdot_insert_batch(
            self.uniffiCloneHandle(),
        FfiConverterSequenceSequenceFloat.lower(data),
        FfiConverterSequenceUInt64.lower(ids),$0
    )
}
}
    
open func isEmpty()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexdot_is_empty(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func len()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexdot_len(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func save(directory: String, basename: String)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexdot_save(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),$0
    )
}
}
    
open func search(query: [Float], k: UInt32, efSearch: UInt32)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexdot_search(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(query),
        FfiConverterUInt32.lower(k),
        FfiConverterUInt32.lower(efSearch),$0
    )
})
}
    
open func setSearchingMode(enabled: Bool)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexdot_set_searching_mode(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(enabled),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHnswIndexDot: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HnswIndexDot

    public static func lift(_ handle: UInt64) throws -> HnswIndexDot {
        return HnswIndexDot(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HnswIndexDot) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HnswIndexDot {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HnswIndexDot, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexDot_lift(_ handle: UInt64) throws -> HnswIndexDot {
    return try FfiConverterTypeHnswIndexDot.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexDot_lower(_ value: HnswIndexDot) -> UInt64 {
    return FfiConverterTypeHnswIndexDot.lower(value)
}






public protocol HnswIndexL1Protocol: AnyObject, Sendable {
    
    func getDimension()  -> UInt32
    
    func insert(data: [Float], id: UInt64) throws 
    
    func insertBatch(data: [[Float]], ids: [UInt64]) throws 
    
    func isEmpty() throws  -> Bool
    
    func len() throws  -> UInt64
    
    func save(directory: String, basename: String) throws 
    
    func search(query: [Float], k: UInt32, efSearch: UInt32) throws  -> [SearchResult]
    
    func setSearchingMode(enabled: Bool) throws 
    
}
open class HnswIndexL1: HnswIndexL1Protocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_hnsw_fn_clone_hnswindexl1(self.handle, $0) }
    }
public convenience init(maxNbConnection: UInt32, maxElements: UInt64, maxLayer: UInt32, efConstruction: UInt32, dimension: UInt32) {
    let handle =
        try! rustCall() {
    uniffi_hnsw_fn_constructor_hnswindexl1_new(
        FfiConverterUInt32.lower(maxNbConnection),
        FfiConverterUInt64.lower(maxElements),
        FfiConverterUInt32.lower(maxLayer),
        FfiConverterUInt32.lower(efConstruction),
        FfiConverterUInt32.lower(dimension),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_hnsw_fn_free_hnswindexl1(handle, $0) }
    }

    
public static func load(directory: String, basename: String, dimension: UInt32)throws  -> HnswIndexL1  {
    return try  FfiConverterTypeHnswIndexL1_lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_constructor_hnswindexl1_load(
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),
        FfiConverterUInt32.lower(dimension),$0
    )
})
}
    

    
open func getDimension() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_hnsw_fn_method_hnswindexl1_get_dimension(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func insert(data: [Float], id: UInt64)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl1_insert(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(data),
        FfiConverterUInt64.lower(id),$0
    )
}
}
    
open func insertBatch(data: [[Float]], ids: [UInt64])throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl1_insert_batch(
            self.uniffiCloneHandle(),
        FfiConverterSequenceSequenceFloat.lower(data),
        FfiConverterSequenceUInt64.lower(ids),$0
    )
}
}
    
open func isEmpty()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl1_is_empty(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func len()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl1_len(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func save(directory: String, basename: String)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl1_save(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),$0
    )
}
}
    
open func search(query: [Float], k: UInt32, efSearch: UInt32)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl1_search(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(query),
        FfiConverterUInt32.lower(k),
        FfiConverterUInt32.lower(efSearch),$0
    )
})
}
    
open func setSearchingMode(enabled: Bool)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl1_set_searching_mode(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(enabled),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHnswIndexL1: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HnswIndexL1

    public static func lift(_ handle: UInt64) throws -> HnswIndexL1 {
        return HnswIndexL1(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HnswIndexL1) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HnswIndexL1 {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HnswIndexL1, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexL1_lift(_ handle: UInt64) throws -> HnswIndexL1 {
    return try FfiConverterTypeHnswIndexL1.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexL1_lower(_ value: HnswIndexL1) -> UInt64 {
    return FfiConverterTypeHnswIndexL1.lower(value)
}






public protocol HnswIndexL2Protocol: AnyObject, Sendable {
    
    func getDimension()  -> UInt32
    
    func insert(data: [Float], id: UInt64) throws 
    
    func insertBatch(data: [[Float]], ids: [UInt64]) throws 
    
    func isEmpty() throws  -> Bool
    
    func len() throws  -> UInt64
    
    func save(directory: String, basename: String) throws 
    
    func search(query: [Float], k: UInt32, efSearch: UInt32) throws  -> [SearchResult]
    
    func setSearchingMode(enabled: Bool) throws 
    
}
open class HnswIndexL2: HnswIndexL2Protocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_hnsw_fn_clone_hnswindexl2(self.handle, $0) }
    }
public convenience init(maxNbConnection: UInt32, maxElements: UInt64, maxLayer: UInt32, efConstruction: UInt32, dimension: UInt32) {
    let handle =
        try! rustCall() {
    uniffi_hnsw_fn_constructor_hnswindexl2_new(
        FfiConverterUInt32.lower(maxNbConnection),
        FfiConverterUInt64.lower(maxElements),
        FfiConverterUInt32.lower(maxLayer),
        FfiConverterUInt32.lower(efConstruction),
        FfiConverterUInt32.lower(dimension),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_hnsw_fn_free_hnswindexl2(handle, $0) }
    }

    
public static func load(directory: String, basename: String, dimension: UInt32)throws  -> HnswIndexL2  {
    return try  FfiConverterTypeHnswIndexL2_lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_constructor_hnswindexl2_load(
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),
        FfiConverterUInt32.lower(dimension),$0
    )
})
}
    

    
open func getDimension() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_hnsw_fn_method_hnswindexl2_get_dimension(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func insert(data: [Float], id: UInt64)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl2_insert(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(data),
        FfiConverterUInt64.lower(id),$0
    )
}
}
    
open func insertBatch(data: [[Float]], ids: [UInt64])throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl2_insert_batch(
            self.uniffiCloneHandle(),
        FfiConverterSequenceSequenceFloat.lower(data),
        FfiConverterSequenceUInt64.lower(ids),$0
    )
}
}
    
open func isEmpty()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl2_is_empty(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func len()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl2_len(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func save(directory: String, basename: String)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl2_save(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(directory),
        FfiConverterString.lower(basename),$0
    )
}
}
    
open func search(query: [Float], k: UInt32, efSearch: UInt32)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl2_search(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(query),
        FfiConverterUInt32.lower(k),
        FfiConverterUInt32.lower(efSearch),$0
    )
})
}
    
open func setSearchingMode(enabled: Bool)throws   {try rustCallWithError(FfiConverterTypeHnswError_lift) {
    uniffi_hnsw_fn_method_hnswindexl2_set_searching_mode(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(enabled),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHnswIndexL2: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HnswIndexL2

    public static func lift(_ handle: UInt64) throws -> HnswIndexL2 {
        return HnswIndexL2(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HnswIndexL2) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HnswIndexL2 {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HnswIndexL2, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexL2_lift(_ handle: UInt64) throws -> HnswIndexL2 {
    return try FfiConverterTypeHnswIndexL2.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswIndexL2_lower(_ value: HnswIndexL2) -> UInt64 {
    return FfiConverterTypeHnswIndexL2.lower(value)
}




public struct SearchResult: Equatable, Hashable {
    public var id: UInt64
    public var distance: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt64, distance: Float) {
        self.id = id
        self.distance = distance
    }

    
}

#if compiler(>=6)
extension SearchResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                id: FfiConverterUInt64.read(from: &buf), 
                distance: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterFloat.write(value.distance, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DistanceType: Equatable, Hashable {
    
    case l2
    case cosine
    case l1
    case dot



}

#if compiler(>=6)
extension DistanceType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDistanceType: FfiConverterRustBuffer {
    typealias SwiftType = DistanceType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DistanceType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .l2
        
        case 2: return .cosine
        
        case 3: return .l1
        
        case 4: return .dot
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DistanceType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .l2:
            writeInt(&buf, Int32(1))
        
        
        case .cosine:
            writeInt(&buf, Int32(2))
        
        
        case .l1:
            writeInt(&buf, Int32(3))
        
        
        case .dot:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDistanceType_lift(_ buf: RustBuffer) throws -> DistanceType {
    return try FfiConverterTypeDistanceType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDistanceType_lower(_ value: DistanceType) -> RustBuffer {
    return FfiConverterTypeDistanceType.lower(value)
}



public enum HnswError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case IoError(message: String)
    
    case LockError(message: String)
    
    case EmptyIndex(message: String)
    
    case DimensionMismatch(message: String)
    
    case ReloadError(message: String)
    
    case DumpError(message: String)
    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension HnswError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHnswError: FfiConverterRustBuffer {
    typealias SwiftType = HnswError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HnswError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .IoError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .LockError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .EmptyIndex(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .DimensionMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .ReloadError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .DumpError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HnswError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .IoError(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .LockError(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .EmptyIndex(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .DimensionMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .ReloadError(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .DumpError(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswError_lift(_ buf: RustBuffer) throws -> HnswError {
    return try FfiConverterTypeHnswError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHnswError_lower(_ value: HnswError) -> RustBuffer {
    return FfiConverterTypeHnswError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    public static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [SearchResult]

    public static func write(_ value: [SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [[Float]]

    public static func write(_ value: [[Float]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[Float]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[Float]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceFloat.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_hnsw_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_get_dimension() != 34712) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_insert() != 16349) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_insert_batch() != 28404) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_is_empty() != 1543) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_len() != 15997) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_save() != 50644) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_search() != 13338) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexcosine_set_searching_mode() != 58904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_get_dimension() != 28306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_insert() != 57933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_insert_batch() != 6031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_is_empty() != 15572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_len() != 24375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_save() != 27010) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_search() != 1649) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexdot_set_searching_mode() != 24194) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_get_dimension() != 48603) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_insert() != 30694) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_insert_batch() != 26027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_is_empty() != 59727) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_len() != 54904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_save() != 64943) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_search() != 43132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl1_set_searching_mode() != 64270) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_get_dimension() != 23269) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_insert() != 55475) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_insert_batch() != 25817) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_is_empty() != 51521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_len() != 25979) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_save() != 22271) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_search() != 14352) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_method_hnswindexl2_set_searching_mode() != 1290) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexcosine_load() != 60188) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexcosine_new() != 40101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexdot_load() != 23668) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexdot_new() != 29965) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexl1_load() != 3319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexl1_new() != 32705) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexl2_load() != 39141) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hnsw_checksum_constructor_hnswindexl2_new() != 5001) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureHnswInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all